class MyHeader extends HTMLElement {

	connectedCallback(){
		this.innerHTML = '<header> <div class="header-area "> <div id="sticky-header" class="main-header-area"> <div class="container-fluid"> <div class="header_bottom_border"> <div class="row align-items-center"> <div class="col-xl-2 col-lg-2"> <div class="logo"> <a href="index.html"> <img src="img/IH.png" alt="Indian Holidays & Hotels"> </a> </div> </div> <div class="col-xl-6 col-lg-6"> <div class="main-menu d-none d-lg-block"> <nav> <ul id="navigation"> <li><a class="active" href="index.html">home</a></li> <li><a href="about.html">About</a></li> <li><a href="#">Destinations <i class="ti-angle-down"></i></a> <ul class="submenu"> <li><a href="#">Domestic <i class="ti-angle-down"></i></a> <ul class="submenu child"> <li><a href="evergreen-gujarat-tour-package.html">Gujarat</a></li> <li><a href="goa-tour-package.html">Goa</a></li> <li><a href="himachal-tour-package.html">Himachal</a></li> <li><a href="jaisalmer-tour-package.html">Jaisalmer</a></li> <li><a href="kashmir-honeymoon-tour-package.html">Kashmir</a></li> <li><a href="kerala-evergreen-tour-package.html">Kerala</a></li> <li><a href="leh-tour-package.html">Leh</a></li> <li><a href="sikkim-tour-package.html">Sikkim</a></li> <li><a href="andaman-tour-package.html">Andaman</a></li> </ul> </li> <li><a href="#">International <i class="ti-angle-down"></i></a> <ul class="submenu child"> <li><a href="dubai-tour-package.html">Dubai</a></li> </ul> </li> </ul> </li> <li><a href="rann-of-kutch-tour-package.html">Rann Utsav </a></li> <li><a href="statue-of-unity-tour-package.html">Staue Of Unity </a></li> <li><a href="contact.html">Contact</a></li> </ul> </nav> </div> </div> <div class="col-xl-4 col-lg-4 d-none d-lg-block"> <div class="social_wrap d-flex align-items-center justify-content-end"> <div class="number"> <p> <i class="fa fa-phone"></i> +91 7017466773</p> </div> <div class="social_links d-none d-xl-block"> <ul> <li><a href="https://www.instagram.com/indianholidaysandhotels/" target="_blank"> <i class="fa fa-instagram"></i> </a></li> <!-- <li><a href="#"> <i class="fa fa-linkedin"></i> </a></li> --> <li><a href="https://www.facebook.com/indianholidaysandhotels/" target="_blank"> <i class="fa fa-facebook"></i> </a></li> <!-- <li><a href="#"> <i class="fa fa-google-plus"></i> </a></li> --> </ul> </div> </div> </div> <div class="col-12"> <div class="mobile_menu d-block d-lg-none"></div> </div> </div> </div> </div> </div> </div> </header>'
	}
}

customElements.define('my-header', MyHeader)

class MyFooter extends HTMLElement{

	connectedCallback(){
		this.innerHTML = '<footer class="footer"> <div class="footer_top"> <div class="container"> <div class="row"> <div class="col-xl-4 col-md-6 col-lg-4 "> <div class="footer_widget"> <div class="footer_logo"> <a href="index.html" style="color: #FFF;"> Indian Holidays & Hotels </a> </div> <p>201, Vraj Apartment, Nr Naranpura Railway Crossing, <br> Ahmedabad INDIA 380013 <br> <a href="#">+91 7017466773</a> <br> <a href="#">info@indianholidayss.com</a> </p> <div class="socail_links"> <ul> <li><a href="https://www.facebook.com/indianholidaysandhotels/"> <i class="fa fa-facebook"></i> </a></li> <li><a href="https://www.instagram.com/indianholidaysandhotels/"> <i class="fa fa-instagram"></i> </a></li> </ul> </div> </div> </div> <div class="col-xl-2 col-md-6 col-lg-2"> <div class="footer_widget"> <h3 class="footer_title"> Company </h3> <ul class="links"> <li><a href="index.html">Home</a></li> <li><a href="about.html">About</a></li> <li><a href="contact.html"> Contact</a></li> </ul> </div> </div> <div class="col-xl-3 col-md-6 col-lg-3"> <div class="footer_widget"> <h3 class="footer_title"> Popular destination </h3> <ul class="links double_links"> <li><a href="saurashtra-darshan-tour.html">Saurashtra</a></li> <li><a href="statue-of-unity-tour-package.html">Statue Of Unity</a></li> <li><a href="rann-of-kutch-tour-package.html">Rann of Kutch</a></li> <li><a href="evergreen-gujarat-tour-package.html">Evergreen Gujarat</a></li> <li><a href="goa-tour-package-from-mumbai.html">Goa</a></li> <li><a href="kashmir-sonmarg-tour-package.html">Kashmir</a></li> <li><a href="andaman-tour-package.html">Andaman</a></li> <li><a href="dubai-tour-package.html">Dubai</a></li> </ul> </div> </div> <div class="col-xl-3 col-md-6 col-lg-3"> <div class="footer_widget"> <h3 class="footer_title"> Instagram </h3> <div class="instagram_feed"> <div class="single_insta"> <a href="#"> <img src="img/instagram/1.png" alt=""> </a> </div> <div class="single_insta"> <a href="#"> <img src="img/instagram/2.png" alt=""> </a> </div> <div class="single_insta"> <a href="#"> <img src="img/instagram/3.png" alt=""> </a> </div> <div class="single_insta"> <a href="#"> <img src="img/instagram/4.png" alt=""> </a> </div> <div class="single_insta"> <a href="#"> <img src="img/instagram/5.png" alt=""> </a> </div> <div class="single_insta"> <a href="#"> <img src="img/instagram/6.png" alt=""> </a> </div> </div> </div> </div> </div> </div> </div> <div class="copy-right_text"> <div class="container"> <div class="footer_border"></div> <div class="row"> <div class="col-xl-12"> <p class="copy_right text-center"> Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved </p> </div> </div> </div> </div> </footer>'
	}
}

customElements.define('my-footer', MyFooter)

class Testimonial extends HTMLElement{

	connectedCallback(){
		this.innerHTML = '<div class="testimonial_area"> <div class="container"> <div class="row"> <div class="col-xl-12"> <div class="testmonial_active owl-carousel"> <div class="single_carousel"> <div class="row justify-content-center"> <div class="col-lg-8"> <div class="single_testmonial text-center"> <div class="author_thumb"> <img src="img/testmonial/author.png" alt=""> </div> <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p> <div class="testmonial_author"> <h3>- Micky Mouse</h3> </div> </div> </div> </div> </div> <div class="single_carousel"> <div class="row justify-content-center"> <div class="col-lg-8"> <div class="single_testmonial text-center"> <div class="author_thumb"> <img src="img/testmonial/author.png" alt=""> </div> <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p> <div class="testmonial_author"> <h3>- Tom Mouse</h3> </div> </div> </div> </div> </div> <div class="single_carousel"> <div class="row justify-content-center"> <div class="col-lg-8"> <div class="single_testmonial text-center"> <div class="author_thumb"> <img src="img/testmonial/author.png" alt=""> </div> <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p> <div class="testmonial_author"> <h3>- Jerry Mouse</h3> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div>'
	}
}

customElements.define('my-testimonial', Testimonial)

class TravelVariation extends HTMLElement{

	connectedCallback(){

		this.innerHTML = '<div class="travel_variation_area"> <div class="container"> <div class="row"> <div class="col-lg-4 col-md-6"> <div class="single_travel text-center"> <div class="icon"> <img src="img/svg_icon/1.svg" alt=""> </div> <h3>Comfortable Journey</h3> <p>We serves you with the Comfortable Journey you have never imagine </p> </div> </div> <div class="col-lg-4 col-md-6"> <div class="single_travel text-center"> <div class="icon"> <img src="img/svg_icon/2.svg" alt=""> </div> <h3>Luxuries Hotel</h3> <p>We provides you the most Luxuries Hotels for your Best experience</p> </div> </div> <div class="col-lg-4 col-md-6"> <div class="single_travel text-center"> <div class="icon"> <img src="img/svg_icon/3.svg" alt=""> </div> <h3>Travel Guide</h3> <p>We Guides you with the best travel plans which makes you vacation more enjoyable.</p> </div> </div> </div> </div> </div>'
	}
}

customElements.define('my-travelvariation', TravelVariation)

